// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"github.com/tal-tech/go-zero/rest"
	"net/http"
	"petclinic/internal/service"
)

func RegisterHandlers(server *rest.Server, serverCtx *service.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/users/id/:userId",
				Handler: GetUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/create",
				Handler: CreateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/vet",
				Handler: GetVets(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/vet/new",
				Handler: NewVetForm(serverCtx),
			},
		},
	)
}
